language: node_js

node_js:
  - "8.11.1"

before_deploy: "NODE_ENV=production npm run build"

deploy:
  provider: pages
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  email: firefoxic.arts@gmail.com
  name: firefoxic
  on:
    branch: master
